name: 'Verify Package Version (npm)'
author: '@tcurdt'
description: 'Check and extract current version from package descriptor and compare it to the current tag'

inputs:
  file:
    description: 'path to package.json'
    default: './package.json'
  prefix:
    description: 'tag prefix'
    default: 'refs/tags/v'

outputs:
  version:
    description: 'version extracted from file'

runs:
  using: 'node20'
  main: 'dist/index.js'
