name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      # - name: Unit Tests
      #   run: npm run test

      - name: Integration Test
        uses: ./
        with:
          file: test/package.json
