name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Dist
        run: npm run dist

      - name: Env
        run: env

      - name: Integration Test
        uses: ./
        with:
          file: test/package.json
        id: debug

      - name: Env
        run: env

      - name: Output
        run: echo "version=${{ steps.debug.outputs.version }}"
